apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep2
  namespace: ls6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
          name: multiport
        env:
        - name: HTTP_PORT
          value: "80"
        volumeMounts:
        - name: vol1
          mountPath: /input
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ls6
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi