apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
      initContainers:
      - name: init-test
        image: busybox
        command: ['sh', '-c', 'until nslookup web-svc.default.svc.cluster.local; do echo waiting for web-svc; sleep 5; done;']