apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
          name: multiport
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
---
apiVersion: v1
kind: Service
metadata:
  name: nmulti-svc
spec:
  selector:
    app: multi
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: multi
    port: 8080
    protocol: TCP
    targetPort: multiport