---
apiVersion: v1
kind: Service
metadata:
  name: multi-svc-np
spec:
  selector:
    app: multi
  ports:
  - name: web
    nodePort: 30001
    port: 80
  - name: multi
    nodePort: 30002
    port: 8080
  type: NodePort