kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: cache
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: cache
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8080
  policyTypes:
  - Egress
